################################################################################
# RF105 reviewed PM2.5 midline/endline explainer figures
#
# Purpose:
#   Create diagnostic figures that help explain why the reviewed PM2.5 rDiD
#   analysis shows a clearer intervention-associated difference at midline than
#   at endline.
#
# Inputs:
#   4_data/clean_final/pm25_pats_refugee_indoor.rds
#   4_data/clean_final/survey_refugee_household.rds
#   7_tables/RF105_reviewed_YYYYMMDD/rdid_xgboost_all_results_reviewed.csv
#   7_tables/pm25_ambient_adjusted_YYYYMMDD/
#     pm25_household_window_analysis_dataset_deidentified.csv, if available
#
# Outputs:
#   7_tables/RF105_reviewed_YYYYMMDD/pm25_explainer_*.csv
#   6_figures/RF105_reviewed_YYYYMMDD/pm25_explainer_*.png
################################################################################

get_script_dir <- function() {
  cmd_args <- commandArgs(trailingOnly = FALSE)
  file_arg <- grep("^--file=", cmd_args, value = TRUE)

  if (length(file_arg) == 1) {
    return(dirname(normalizePath(sub("^--file=", "", file_arg),
                                 winslash = "/", mustWork = FALSE)))
  }

  source_files <- vapply(sys.frames(), function(frame) {
    if (!is.null(frame$ofile)) frame$ofile else NA_character_
  }, character(1))
  source_files <- source_files[!is.na(source_files)]

  if (length(source_files) > 0) {
    return(dirname(normalizePath(source_files[[length(source_files)]],
                                 winslash = "/", mustWork = FALSE)))
  }

  getwd()
}

script_dir <- get_script_dir()
config_file <- file.path(script_dir, "0_RF105_reviewed_config.R")
if (!file.exists(config_file)) {
  config_file <- file.path("5_analysis_RF105", "reviewed", "0_RF105_reviewed_config.R")
}
source(config_file)

first_nonmissing <- function(x) {
  x <- x[!is.na(x)]
  if (length(x) == 0) return(NA)
  x[[1]]
}

as_number <- function(x) {
  suppressWarnings(as.numeric(x))
}

mean_ci <- function(x) {
  x <- x[is.finite(x) & !is.na(x)]
  if (length(x) == 0) {
    return(tibble(mean = NA_real_, conf.low = NA_real_, conf.high = NA_real_))
  }
  se <- stats::sd(x) / sqrt(length(x))
  tibble(
    mean = mean(x),
    conf.low = mean(x) - stats::qt(0.975, df = length(x) - 1) * se,
    conf.high = mean(x) + stats::qt(0.975, df = length(x) - 1) * se
  )
}

find_latest_ambient_dir <- function() {
  candidate_dirs <- list.dirs(file.path(project_root, "7_tables"),
                              full.names = TRUE, recursive = FALSE)
  candidate_dirs <- candidate_dirs[
    str_detect(basename(candidate_dirs), "^pm25_ambient_adjusted_")
  ]
  if (length(candidate_dirs) == 0) {
    return(NA_character_)
  }
  candidate_dirs[[order(basename(candidate_dirs), decreasing = TRUE)[[1]]]]
}

################################################################################
# Data-source audit
################################################################################

rdid_script_file <- file.path(script_dir, "4_rdid_xgboost_reviewed.R")
ambient_script_file <- file.path(
  project_root,
  "5_analysis",
  "6_PM_analysis",
  "3_pm25_ambient_adjusted_analysis.R"
)

ambient_table_dir <- file.path(
  project_root,
  "7_tables",
  paste0("pm25_ambient_adjusted_", date_stamp)
)
if (!dir.exists(ambient_table_dir)) {
  ambient_table_dir <- find_latest_ambient_dir()
}

ambient_household_file <- file.path(
  ambient_table_dir,
  "pm25_household_window_analysis_dataset_deidentified.csv"
)
ambient_rdid_household_file <- file.path(
  ambient_table_dir,
  "pm25_rdid_ambient_excess_household_timepoint_internal.csv"
)

pm25_source_audit <- tibble(
  reviewed_pm_rdid_script = rdid_script_file,
  reviewed_pm_rdid_input = ambient_rdid_household_file,
  ambient_adjusted_script = ambient_script_file,
  ambient_adjusted_household_window_output = ambient_household_file,
  ambient_adjusted_rdid_household_output = ambient_rdid_household_file,
  reviewed_rdid_uses_ambient_adjusted_output = TRUE,
  note = paste(
    "The reviewed RF105 rDiD PM2.5 model now uses the ambient-adjusted",
    "household-timepoint file generated by 3_pm25_ambient_adjusted_analysis.R.",
    "The default modeled PM outcome is indoor PM2.5 minus 0.75 times",
    "concurrent ambient PM2.5."
  )
)

write_reviewed_csv(
  pm25_source_audit,
  "pm25_explainer_data_source_audit_reviewed.csv",
  subfolder = "qa"
)

################################################################################
# Paired household rDiD panels from the same source as reviewed PM rDiD
################################################################################

survey_raw <- readRDS(file_survey_refugee_household) %>%
  add_rf105_aliases() %>%
  clean_timepoint_arm()

analysis_population <- make_analysis_population(survey_raw, id_var = "fcn_id")

baseline_covars <- analysis_population$all_deduplicated %>%
  filter(timepoint == "baseline") %>%
  transmute(
    fcn_id = as.character(fcn_id),
    baseline_survey_arm = case_when(
      study_arm_overall == "intervention" ~ "intervention",
      study_arm_overall == "comparison" ~ "comparison",
      TRUE ~ NA_character_
    )
  ) %>%
  group_by(fcn_id) %>%
  summarise(
    baseline_survey_arm = as.character(first_nonmissing(baseline_survey_arm)),
    .groups = "drop"
  ) %>%
  filter(!is.na(baseline_survey_arm))

if (!file.exists(ambient_rdid_household_file)) {
  stop(
    "Missing ambient-adjusted PM household-timepoint file: ",
    ambient_rdid_household_file,
    ". Run 5_analysis_RF105/6_PM_analysis/3_pm25_ambient_adjusted_analysis.R first.",
    call. = FALSE
  )
}

pm_household <- readr::read_csv(
  ambient_rdid_household_file,
  show_col_types = FALSE
) %>%
  clean_timepoint_arm() %>%
  transmute(
    fcn_id = as.character(fcn_id),
    timepoint,
    collection_date_min = as.Date(collection_date_min),
    collection_date_max = as.Date(collection_date_max),
    n_monitor_files = as_number(n_monitor_files),
    pm25_adjusted_default = as_number(indoor_minus_ambient_material_default)
  ) %>%
  filter(
    !is.na(fcn_id),
    fcn_id != "",
    !is.na(timepoint),
    !is.na(pm25_adjusted_default)
  )
make_pm_panel <- function(followup_timepoint, contrast_label) {
  baseline_pm <- pm_household %>%
    filter(timepoint == "baseline") %>%
    transmute(
      fcn_id,
      pm25_baseline = pm25_adjusted_default,
      baseline_collection_date_min = collection_date_min,
      baseline_collection_date_max = collection_date_max,
      baseline_monitor_files = n_monitor_files
    )

  followup_pm <- pm_household %>%
    filter(timepoint == followup_timepoint) %>%
    transmute(
      fcn_id,
      pm25_followup = pm25_adjusted_default,
      followup_collection_date_min = collection_date_min,
      followup_collection_date_max = collection_date_max,
      followup_monitor_files = n_monitor_files
    )

  baseline_covars %>%
    inner_join(baseline_pm, by = "fcn_id") %>%
    inner_join(followup_pm, by = "fcn_id") %>%
    mutate(
      contrast = contrast_label,
      followup_timepoint = followup_timepoint,
      pm25_change_followup_minus_baseline = pm25_followup - pm25_baseline,
      pm25_reduction_baseline_minus_followup = pm25_baseline - pm25_followup
    )
}

pm_paired_panels <- bind_rows(
  make_pm_panel("midline", "primary_baseline_midline"),
  make_pm_panel("endline", "secondary_baseline_endline")
) %>%
  mutate(
    baseline_survey_arm = factor(baseline_survey_arm, levels = arm_levels),
    contrast_label = recode(
      contrast,
      primary_baseline_midline = "Primary: baseline to midline",
      secondary_baseline_endline = "Secondary: baseline to endline"
    )
  )

paired_change_summary <- pm_paired_panels %>%
  group_by(contrast, contrast_label, baseline_survey_arm) %>%
  summarise(
    n_households = n_distinct(fcn_id),
    mean_baseline_pm25 = mean(pm25_baseline, na.rm = TRUE),
    mean_followup_pm25 = mean(pm25_followup, na.rm = TRUE),
    median_baseline_pm25 = median(pm25_baseline, na.rm = TRUE),
    median_followup_pm25 = median(pm25_followup, na.rm = TRUE),
    mean_change_followup_minus_baseline =
      mean(pm25_change_followup_minus_baseline, na.rm = TRUE),
    median_change_followup_minus_baseline =
      median(pm25_change_followup_minus_baseline, na.rm = TRUE),
    mean_reduction_baseline_minus_followup =
      mean(pm25_reduction_baseline_minus_followup, na.rm = TRUE),
    median_reduction_baseline_minus_followup =
      median(pm25_reduction_baseline_minus_followup, na.rm = TRUE),
    .groups = "drop"
  )

write_reviewed_csv(
  paired_change_summary,
  "pm25_explainer_paired_change_summary_reviewed.csv"
)

rdid_pm_results <- readr::read_csv(
  file.path(dir_tables_reviewed, "rdid_xgboost_all_results_reviewed.csv"),
  show_col_types = FALSE
) %>%
  filter(outcome == "pm25_ambient_excess_default") %>%
  mutate(
    contrast_label = recode(
      contrast,
      primary_baseline_midline = "Primary: baseline to midline",
      secondary_baseline_endline = "Secondary: baseline to endline"
    ),
    rdid_label = paste0(
      "rDiD/XGBoost: ",
      round(estimate, 1),
      " [",
      round(conf.low, 1),
      ", ",
      round(conf.high, 1),
      "]"
    )
  )

plot_limits <- pm_paired_panels %>%
  group_by(contrast_label) %>%
  summarise(
    y = max(pm25_change_followup_minus_baseline, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  left_join(select(rdid_pm_results, contrast_label, rdid_label),
            by = "contrast_label") %>%
  mutate(
    x = 1.5,
    y = y + 35
  )

paired_change_figure <- ggplot(
  pm_paired_panels,
  aes(
    x = baseline_survey_arm,
    y = pm25_change_followup_minus_baseline,
    color = baseline_survey_arm
  )
) +
  geom_hline(yintercept = 0, color = "grey35", linewidth = 0.45) +
  geom_boxplot(width = 0.45, outlier.shape = NA, alpha = 0.12) +
  geom_jitter(width = 0.08, height = 0, alpha = 0.45, size = 1.7) +
  stat_summary(
    fun = mean,
    geom = "point",
    shape = 23,
    fill = "white",
    color = "black",
    size = 2.8
  ) +
  geom_text(
    data = plot_limits,
    aes(x = x, y = y, label = rdid_label),
    inherit.aes = FALSE,
    size = 3.2,
    lineheight = 0.95
  ) +
  facet_wrap(~ contrast_label, scales = "free_y") +
  scale_color_manual(
    values = c(comparison = "#4E79A7", intervention = "#D55E00")
  ) +
  labs(
    x = NULL,
    y = "Follow-up minus baseline ambient-adjusted indoor PM2.5 (ug/m3)",
    color = NULL,
    title = "Paired household ambient-adjusted PM2.5 changes by analysis contrast",
    subtitle = "Negative values indicate lower PM2.5 at follow-up than baseline",
    caption = paste(
      "Household means use the default adjusted PM source: indoor PM2.5 minus 0.75 x concurrent ambient PM2.5",
      "as the reviewed PM2.5 rDiD/XGBoost analysis."
    )
  ) +
  theme_bw(base_size = 11) +
  theme(
    legend.position = "bottom",
    panel.grid.minor = element_blank(),
    strip.background = element_rect(fill = "grey92", color = "grey75")
  )

save_reviewed_plot(
  paired_change_figure,
  "pm25_explainer_paired_household_change_reviewed.png",
  width = 10,
  height = 5.6
)

################################################################################
# Ambient context figure from the ambient-adjusted household-window dataset
################################################################################

if (file.exists(ambient_household_file)) {
  ambient_household <- readr::read_csv(
    ambient_household_file,
    show_col_types = FALSE
  ) %>%
    mutate(
      timepoint = factor(timepoint, levels = timepoint_levels),
      study_arm_overall = factor(study_arm_overall, levels = arm_levels),
      has_concurrent_ambient = as.logical(has_concurrent_ambient)
    ) %>%
    filter(has_concurrent_ambient)

  ambient_context_long <- ambient_household %>%
    select(
      timepoint, study_arm_overall,
      indoor_mean_pm,
      ambient_all_mean_pm,
      indoor_minus_ambient_material_default
    ) %>%
    pivot_longer(
      cols = c(
        indoor_mean_pm,
        ambient_all_mean_pm,
        indoor_minus_ambient_material_default
      ),
      names_to = "measure",
      values_to = "pm25"
    ) %>%
    mutate(
      measure = recode(
        measure,
        indoor_mean_pm = "Indoor household mean",
        ambient_all_mean_pm = "Concurrent ambient mean",
        indoor_minus_ambient_material_default =
          "Indoor minus 0.75 x ambient"
      ),
      measure = factor(
        measure,
        levels = c(
          "Indoor household mean",
          "Concurrent ambient mean",
          "Indoor minus 0.75 x ambient"
        )
      )
    )

  ambient_context_summary <- ambient_context_long %>%
    group_by(timepoint, study_arm_overall, measure) %>%
    summarise(
      n_windows = n(),
      median_pm25 = median(pm25, na.rm = TRUE),
      p25_pm25 = quantile(pm25, 0.25, na.rm = TRUE, names = FALSE),
      p75_pm25 = quantile(pm25, 0.75, na.rm = TRUE, names = FALSE),
      mean_pm25 = mean(pm25, na.rm = TRUE),
      .groups = "drop"
    )

  write_reviewed_csv(
    ambient_context_summary,
    "pm25_explainer_ambient_context_summary_reviewed.csv"
  )

  ambient_context_figure <- ggplot(
    ambient_context_summary,
    aes(
      x = timepoint,
      y = median_pm25,
      ymin = p25_pm25,
      ymax = p75_pm25,
      color = study_arm_overall,
      group = study_arm_overall
    )
  ) +
    geom_hline(yintercept = 0, color = "grey70", linewidth = 0.35) +
    geom_pointrange(
      position = position_dodge(width = 0.45),
      linewidth = 0.55
    ) +
    geom_line(position = position_dodge(width = 0.45), linewidth = 0.45) +
    facet_wrap(~ measure, scales = "free_y") +
    scale_color_manual(
      values = c(comparison = "#4E79A7", intervention = "#D55E00")
    ) +
    labs(
      x = NULL,
      y = "Median PM2.5 with IQR (ug/m3)",
      color = "Study arm",
      title = "Indoor PM2.5, concurrent ambient PM2.5, and ambient-excess PM2.5",
      subtitle = "Ambient-adjusted household-window dataset; windows without concurrent ambient data are excluded",
      caption = paste(
        "Ambient-excess measure uses the default 0.75 ambient infiltration/material assumption",
        "from 3_pm25_ambient_adjusted_analysis.R."
      )
    ) +
    theme_bw(base_size = 11) +
    theme(
      legend.position = "bottom",
      panel.grid.minor = element_blank(),
      strip.background = element_rect(fill = "grey92", color = "grey75")
    )

  save_reviewed_plot(
    ambient_context_figure,
    "pm25_explainer_indoor_ambient_excess_by_timepoint_reviewed.png",
    width = 11,
    height = 5.5
  )
} else {
  write_reviewed_csv(
    tibble(
      expected_file = ambient_household_file,
      status = "not_found",
      note = paste(
        "Run 5_analysis_RF105/6_PM_analysis/3_pm25_ambient_adjusted_analysis.R",
        "to generate the ambient-adjusted household-window dataset."
      )
    ),
    "pm25_explainer_ambient_context_missing_reviewed.csv",
    subfolder = "qa"
  )
}
