---
title: "R_Sensor_datapull"
author: "Chris LeBoa"
date: "11/10/2019"
output: pdf_document
---

```{r setup, include=FALSE}
#install.packages("pylr")
#install.packages("readr")

library(tidyverse)
library(plyr)
library(readr)

```

```{r file_paths}
list_of_file_path <- "/Users/ChrisLeBoa/Documents/Stanford School Files /Research/Luby Lab/Bangladesh/Rohingya/Data_sensors/ALL DATA/PATS+"

all_pm_data_path <- "/Users/ChrisLeBoa/Box Sync/Rohingya_sensor_data_pull/Rohingya_sensor_data_all/PATS+Data_20191110.csv"

```


```{r, include=FALSE}
setwd("/Users/ChrisLeBoa/Documents/Stanford School Files /Research/Luby Lab/Bangladesh/Rohingya/Data_sensors/ALL DATA")

```

## File of Pats+ Data
```{r}
list_of_files <-   
  list.files(
    path = list_of_file_path,
    recursive = TRUE, 
    pattern = "*.csv", 
    full.names = TRUE 
  )

all_pm_data <- 
  list_of_files %>%
  set_names(sub(".*/", "", list_of_files)) %>% # added file_name as first column value
  map_dfr(
    ~ read_csv(
      .x,
      col_types = 
        cols("c", "d", "d", "d", "d", "d", "d", "d", "d", "d", "d", "d", "d", "d", "d", "d"),
      skip = 31, 
      col_names = FALSE, 
    ),
    .id = "file_name" # labeled first column with as "file_name"
  ) %>% 
  mutate(
    file_name = str_replace(file_name, "\\..*","")
  ) %>% 
  `colnames<-`(
    c(
      "file_name", "dateTime",	"V_power",	"degC_sys",	"degC_air",	"RH_air",	"degC_CO",	"CO_PPM",	"status",	"ref_sigDel",	"low20avg",	"high320avg",	"motion",	"CO_mV",	"ignore",	"iButton_Temp",	"PM_Estimate"
    )
  ) %>%
  mutate(dateTime_lubridated = lubridate::ymd_hms(dateTime, tz = "Asia/Dhaka", locale = Sys.getlocale("LC_TIME"), truncated = 3)) %>%
  write_csv(all_pm_data_path)

View(all_pm_data)

```

```{r}
class(all_pm_data$dateTime_lubridated)

all_pm_data %>%
  ggplot(aes(dateTime, PM_Estimate, color = file_name)) +
  geom_point(na.rm = TRUE) +
  theme(
    legend.position = "none"
  )
  
```

