---
title: "PM_analysis"
author: "Laura Kwong"
date: "11/06/2019"
output:
  word_document: default
  html_document: default
---
R verion 3.6.1 downloaded 6 Nov 2019


https://cran.r-project.org/web/packages/MakefileR/vignettes/demo.html

sensor_pull_data.R is in the "munge" folder

```{r setup, include=FALSE}
library(tableone)
library(janitor) #tabyl() adorn_...()
library(dplyr)
library(readxl)
library(lubridate)
library(tidyverse)
library(knitr)
library(kableExtra)

knitr::opts_chunk$set(echo = TRUE)

`%notin%` <- Negate(`%in%`)
```

```{r file_paths}
#Input Files
list_of_file_path_pats_pre_intervention <- "C:/Users/lenovo/Google Drive (lakwong@stanford.edu)/Rohingya/Rohingya research - Fuel/Sensors/ALL DATA/Pre_intervention/PATS+"

list_of_file_path_pats_intervention <- "C:/Users/lenovo/Google Drive (lakwong@stanford.edu)/Rohingya/Rohingya research - Fuel/Sensors/ALL DATA/Intervention/PATS+"

list_of_file_path_hapex_pre_intervention <- "C:/Users/lenovo/Google Drive (lakwong@stanford.edu)/Rohingya/Rohingya research - Fuel/Sensors/ALL DATA/Pre-intervention/HAPEX"

list_of_file_path_hapex_intervention <- "C:/Users/lenovo/Google Drive (lakwong@stanford.edu)/Rohingya/Rohingya research - Fuel/Sensors/ALL DATA/Intervention/HAPEX"

### Output Files RDS 
all_pm_data_path_rds <- "C:/Users/lenovo/Google Drive (lakwong@stanford.edu)/Rohingya/Rohingya research - Fuel/Sensors/ALL DATA/PATS+_Data_20191115.rds"

all_hapex_data_path_rds <- "C:/Users/lenovo/Google Drive (lakwong@stanford.edu)/Rohingya/Rohingya research - Fuel/Sensors/ALL DATA/Hapex_Data_20191115.rds"

# Manually move the compiled file into the raw folder of the project

file_pm_data_base <- here::here("data", "raw", "PATS+_Data_20191115.rds")
file_HAPEX_data_base <- here::here("data", "raw", "HAPEX_Data_20191115.rds")
```

## File of Pats+ Data
```{r}
list_of_files_pats_pre_intervention <-   
	list.files(
		path = list_of_file_path_pats_pre_intervention,
		recursive = TRUE, 
		pattern = "*.csv", 
		full.names = TRUE 
	)

list_of_files_pats_intervention <-   
	list.files(
		path = list_of_file_path_pats_intervention,
		recursive = TRUE, 
		pattern = "*.csv", 
		full.names = TRUE 
	)

list_of_files_pats <- c(list_of_files_pats_pre_intervention, list_of_files_pats_intervention)

all_pm_data <- 
	list_of_files_pats %>%
	set_names(sub(".*/", "", list_of_files_pats)) %>% # added file_name as first column value
	map_dfr(
		~ read_csv(
			.x,
			col_types = 
				cols(
					"c", "d", "d", "d", "d", "d", "d", 
					"d", "d", "d", "d", "d", "d", "d", "d", "d"
				),
			skip = 31, 
			col_names = FALSE, 
		),
		.id = "file_name" # labeled first column with as "file_name"
	) %>% 
	select(-X) %>% # I don't know why there is an empty column X at the end
	mutate(
		file_name = str_replace(file_name, "\\..*","")
	) %>% 
	`colnames<-`( # must be exactly `colnames<-`
		c(
			"file_name", "dateTime",	
			"V_power",	"degC_sys",	"degC_air",	"RH_air",	
			"degC_CO",	"CO_PPM",	"status",	"ref_sigDel",	
			"low20avg",	"high320avg",	"motion",	"CO_mV",	
			"ignore",	"iButton_Temp",	"PM_Estimate"
		)
	) 
#  mutate(dateTime_lubridated = lubridate::ymd_hms(dateTime, tz = "Asia/Dhaka", locale = Sys.getlocale("LC_TIME"), truncated = 3)) %>%

all_pm_data %>%
	saveRDS(all_pm_data_path_rds)
```


# Hapex Data 
```{r}
list_of_files_hapex_pre_intervention <-   
	list.files(
		path = list_of_file_path_hapex_pre_intervention,
		recursive = TRUE, 
		pattern = "*.csv", 
		full.names = TRUE 
	)

list_of_files_hapex_intervention <-   
	list.files(
		path = list_of_file_path_hapex_intervention,
		recursive = TRUE, 
		pattern = "*.csv", 
		full.names = TRUE 
	)

list_of_files_hapex <- c(list_of_files_hapex_pre_intervention, list_of_files_hapex_intervention)


all_hapex_data <- 
	list_of_files_hapex %>%
	set_names(sub(".*/", "", list_of_files_hapex)) %>% # added file_name as first column value
	map_dfr(
		~ read_csv(
			.x,
			col_types = 
				cols("c", "d", "d"),
			skip = 29, 
			col_names = FALSE, 
		),
		.id = "file_name" # labeled first column with as "file_name"
	) %>% 
	mutate(
		file_name = str_replace(file_name, "\\..*","")
	) %>% 
	`colnames<-`(
		c(
			"file_name", "timestamp",	"mother_compliance",	"mother_pm"
		)
	) 

all_hapex_data %>%
	saveRDS(all_hapex_data_path_rds)

#   mutate(dateTime_lubridated = lubridate::ymd_hms(dateTime, tz = "Asia/Dhaka", locale = Sys.getlocale("LC_TIME"), truncated = 3)) %>%
```


# WRONG
The date on PM07751B_20190915_0_8wDH21291216 and PM07751B_20190921_0_8wD290417
is 2000-01-01 and onwards -> fix this later and drop for now

# Clean data
Still not clean, must look at google sheet for other adjustments that need to be made. 
```{r load_data, include=FALSE} 
pm_data <- 
	readRDS(file = file_pm_data_base) %>%
	filter(V_power > 3.6) %>% # If the battery voltage is not more than 3.6, the PM manual notes that the reading may not be accurate
	separate(file_name, into = c("PM_monitor", "date", "study_arm", "hh_id_note"), sep = "_", extra = "merge", remove = FALSE) %>% # for some reason if I sep into five columns right away, those with no "note" are missing a study arm
	separate(hh_id_note, into = c("hh_id", "note"), sep = "_", extra = "merge", remove = TRUE) %>% # I do want a variable hh_id_note but first clean up the case (str_to_lower) of the note then recombine.
	
	mutate(
		dateTime = 
			if_else(
				is.na(ymd_hms(dateTime)) == FALSE, 
				ymd_hms(dateTime), 
				mdy_hm(dateTime)
			),
		dateTime_min = round_date(dateTime, unit = "minute"),
		dateTime_hour = round_date(dateTime, unit = "hour"),
		note = str_to_lower(note),
		study_arm =
			if_else(note %in% c("school", "mosque"), "outdoor", study_arm),
		study_arm =
			ordered(
				as.character(study_arm),
				levels = c("0", "1", "outdoor"),
				labels = c("pre-intervention", "intervention", "outdoor")
			),
		note = 
			if_else(is.na(note), "normal", note)
	) %>%
	unite(col = "hh_id_note", c(hh_id, note), remove = FALSE) %>%
	# This is separating by the - in the date rather than the " " between the date and time, like it is supposed to. 
	separate(dateTime_min, into = c("dateTime_min_extraDate", "nearest_min", sep = " "), remove = FALSE) %>%
	separate(dateTime_hour, into = c("dateTime_hour_extraDate", "nearest_hour", sep = " "), remove = FALSE) %>%
	select(-dateTime_hour_extraDate, -dateTime_min_extraDate) %>%
	select(study_arm, hh_id, note, hh_id_note, dateTime, dateTime_min, nearest_min, dateTime_hour, nearest_hour, everything())

pm_data_min <-
	pm_data %>%
	group_by(study_arm, note, hh_id, hh_id_note, dateTime_min) %>%
	summarise_at(
		vars(PM_Estimate),
		list(mean),
		na.rm = TRUE
	) %>% 	
	ungroup()

pm_data_nearest_min <-
	pm_data %>%
	group_by(study_arm, note, hh_id, hh_id_note, nearest_min) %>%
	summarise_at(
		vars(PM_Estimate),
		list(mean),
		na.rm = TRUE
	) %>% 	
	ungroup()

pm_data_hour <-
	pm_data %>%
	group_by(study_arm, note, hh_id, hh_id_note, dateTime_hour) %>%
	summarise_at(
		vars(PM_Estimate),
		list(mean),
		na.rm = TRUE
	) %>%
	ungroup() %>%
	mutate(
		over_100 = if_else(PM_Estimate > 100, 1, 0),
		over_500 = if_else(PM_Estimate > 500, 1, 0)
	)

pm_data_nearest_hour <-
	pm_data %>%
	group_by(study_arm, note, hh_id, hh_id_note, nearest_hour) %>%
	summarise_at(
		vars(PM_Estimate),
		list(mean),
		na.rm = TRUE
	) %>%
	ungroup() %>%
	mutate(
		over_100 = if_else(PM_Estimate > 100, 1, 0),
		over_500 = if_else(PM_Estimate > 500, 1, 0)
	)

pm_data_hour_summary <-
	pm_data_hour %>%
	group_by(study_arm, hh_id, note, hh_id_note) %>%
	summarize_at(
		vars(over_100, over_500),
		funs(sum)
	) %>%
	gather(-c(study_arm, hh_id, note, hh_id_note), key = "indicator", value = "hours")

# head(pm_data)
# View(pm_data)
# pm_data %>% pull(study_arm) %>% unique()
# pm_data %>%
# 	filter(str_detect(file_name, "10G105460")) %>% tail()

```

```{r}
pm_data_min %>%
	filter(hh_id %notin% c("8wDH21291216", "8wD290417")) %>% # Take out of now because have 2000 as the year
	filter(note != "insufficient data") %>%
	ggplot(aes(dateTime_min, PM_Estimate, color = hh_id_note)) +
	geom_line(na.rm = TRUE) +
	# geom_hline(yintercept = 100, color = "blue") + 
	# geom_hline(yintercept = 500, color = "red") +
	theme(
		legend.position = "none"
	) + 
	facet_grid( ~ study_arm)

# pm_data_nearest_min %>%
# 	filter(hh_id %notin% c("8wDH21291216", "8wD290417")) %>% # Take out of now because have 2000 as the year
# 	filter(note != "insufficient data") %>%
# 	ggplot(aes(nearest_minute, PM_Estimate, color = hh_id)) +
# 	geom_line(na.rm = TRUE) +
# 	geom_hline(yintercept = 100, color = "blue") + 
# 	geom_hline(yintercept = 500, color = "red") +
# 	theme(
# 		legend.position = "none"
# 	) + 
# 	facet_grid( ~ study_arm)

pm_data_hour %>%
	filter(hh_id %notin% c("8wDH21291216", "8wD290417")) %>%
	filter(note != "insufficient data") %>%
	ggplot(aes(dateTime_hour, PM_Estimate, color = hh_id_note)) +
	geom_line(na.rm = TRUE) +
	geom_hline(yintercept = 100, color = "blue") + 
	geom_hline(yintercept = 500, color = "red") +
	theme(
		legend.position = "none"
	) + 
	facet_grid( ~ study_arm)

# pm_data_nearest_hour %>%
# 	filter(hh_id %notin% c("8wDH21291216", "8wD290417")) %>%
# 	filter(note != "insufficient data") %>%
# 	ggplot(aes(nearest_hour, PM_Estimate, color = hh_id)) +
# 	geom_line(na.rm = TRUE) +
# 	geom_hline(yintercept = 100, color = "blue") + 
# 	geom_hline(yintercept = 500, color = "red") +
# 	theme(
# 		legend.position = "none"
# 	) + 
# 	facet_grid( ~ study_arm)


pm_data_hour_summary %>%
	filter(note != "qc") %>%
	filter(note != "insufficient data") %>%
	ggplot(aes(y = hours, color = study_arm)) +
	geom_boxplot() +
	scale_color_discrete() + # viridus uses purple and yellow!
	facet_grid(indicator ~ study_arm + note, scales = "free_y")
```

I don't understand why the mosque is so high but this doesn't show up in the "outdoor" graph that I made. 
```{r, fig.height=5, fig.width=10}
# pm_data_hour %>%
# 		filter(hh_id %notin% c("8wDH21291216", "8wD290417")) %>%
# 	filter(hh_id %in% c("10F192735", "4E280686")) %>%
# 	ggplot(aes(dateTime_hour, PM_Estimate, color = hh_id)) +
# 	geom_line(na.rm = TRUE) +
# 	geom_hline(yintercept = 100, color = "blue") + 
# 	geom_hline(yintercept = 500, color = "red") +
# 	theme(
# 		legend.position = "none"
# 	) + 
# 	facet_grid( ~ study_arm, scales = "free_y")

pm_data_min %>%
		filter(hh_id %notin% c("8wDH21291216", "8wD290417")) %>%
	# filter(study_arm == "pre-intervention") %>%
	filter(
		hh_id_note %in% 
				 	c(
	# "10D193579_normal", "10D193579_qc", 
	# "10F113975_normal", "10F113975_qc", 
	# "10G105368_normal", "10G105368_qc"#,
	# "10G105460_normal", "10G105460_qc",
	# "10G108169_normal", "10G108169_qc",
	# "10G116129_normal", "10G116129_qc",
	# "10H286043_normal", "10H286043_qc"#,
	# "8wDI18224646_normal", "8wDI18224646_qc",
	# "8wDI20101777_normal", "8wDI20101777_qc",
	# "8wDI20274944_normal", "8wDI20274944_qc"#,
	# "9G600021_normal", "9G600021_qc",
	# "4E179029_normal", "4E179029_qc",
	# "4E179247_normal", "4E179247_qc",
	# "4E277017_normal", "4E277017_qc",
	# "4E280792_normal", "4E280792_qc",
	# "4F180644_normal", "4F180644_qc",
	# "4E280792_normal", "4E280792_qc",
	"4F180644_normal", "4F180644_qc"#,
	# "4F283027_normal", "4F283027_qc",
	# "4F296441_normal", "4F296441_qc"
	)
	) %>% # PM07745L_20191115_1_4F180644and PM07776R_20191115_1_4F180644_QC; PM07781I_20191115_1_4F296441 and PM07782G_20191115_1_4F296441_QC
	# filter(dateTime_min > "2019-09-25", dateTime_min < "2019-09-26") %>%
	ggplot(aes(dateTime_min, PM_Estimate, color = hh_id_note)) +
	geom_line(na.rm = TRUE) +
	# geom_hline(yintercept = 100, color = "blue") + 
	# geom_hline(yintercept = 500, color = "red") +
	# theme(
	# 	legend.position = "none"
	# ) 
	# facet_grid(hh_id ~ ., scales = "free")
facet_grid(. ~ hh_id, scales = "free")

pm_data_min %>%
		filter(hh_id %notin% c("8wDH21291216", "8wD290417")) %>%
	# filter(study_arm == "pre-intervention") %>%
	filter(
		note %in% c("mosque", "school")
	) %>% # PM07745L_20191115_1_4F180644and PM07776R_20191115_1_4F180644_QC; PM07781I_20191115_1_4F296441 and PM07782G_20191115_1_4F296441_QC
	# filter(dateTime_min > "2019-09-25", dateTime_min < "2019-09-26") %>%
	ggplot(aes(dateTime_min, PM_Estimate, color = hh_id_note)) +
	geom_line(na.rm = TRUE) +
	# geom_hline(yintercept = 100, color = "blue") + 
	# geom_hline(yintercept = 500, color = "red") +
	# theme(
	# 	legend.position = "none"
	# ) 
	# facet_grid(hh_id ~ ., scales = "free")
facet_grid(. ~ hh_id, scales = "free")

# pm_data_min$hh_id_note %>% unique()
```

